# Online softmax

In [45]:
import numpy as np
np.random.seed(42)

In [46]:
C = 100

s = np.random.rand(C)

I1 = np.arange(0, C//2)
I2 = np.arange(C//2, C)
s1 = s[I1]
s2 = s[I2]

s - np.hstack([s1,s2]) # make sure we didn't make a silly error

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
def softmax(z):
    expz = np.exp(z)
    normalizer = np.sum(expz)
    return expz / normalizer, normalizer

In [48]:
C = 100
d = 3
np.random.seed(42)
V = np.random.randn(C, d)

p, n = softmax(s)
p @ V

array([ 0.13778369, -0.16034761,  0.04310764])

In [49]:
p1, n1 = softmax(s1)
O = p1 @ V[I1,:] # not yet correct

In [50]:
p2, n2 = softmax(s2)
#   O2 contrib from 2nd block      O1 contrib from 1st
O = p2 @ V[I2,:] * (n2/ (n1+n2)) + O * (n1/ (n1+n2))
#   update                         previous state

O

array([ 0.13778369, -0.16034761,  0.04310764])