# Online softmax

In [1]:
import numpy as np
np.random.seed(42)

In [2]:
C = 100

s = np.random.rand(C)

I1 = np.arange(0, C//2)
I2 = np.arange(C//2, C)
s1 = s[I1]
s2 = s[I2]

s - np.hstack([s1,s2]) # make sure we didn't make a silly error

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
def softmax(z):
    expz = np.exp(z)
    normalizer = np.sum(expz)
    return expz / normalizer, normalizer

In [4]:
d = 3
np.random.seed(42)
V = np.random.randn(C, d)

p, n = softmax(s)
p @ V

array([ 0.13778369, -0.16034761,  0.04310764])

In [5]:
# block 1
p1, n1 = softmax(s1)
O = p1 @ V[I1,:]

# block 2
p2, n2 = softmax(s2)
O = None # YOUR CODE HERE
O

In [6]:

# expected output

# array([ 0.13778369, -0.16034761,  0.04310764])