### Perceptron Learning Algorithm

In [ ]:
# Imports
import numpy as np

In [ ]:
def perceptron_update(X,y,T):
  w = np.zeros((1,2))
  for t in range(T):
    if y[t] * (np.dot(w,X[t])) <= 0:
      print("Caso else")
      w = w + y[t]*X[t]
    else:
      print("Caso if")
    print(w)

In [ ]:
#X = np.array([[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]])
#y = np.array([1,1,-1,-1,-1,-1,1,1])
#T = 8

X = np.array([[1,0],[1,1],[0,2],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]])
y = np.array([1,1,-1,-1,-1,-1,1,1])
T = 8

perceptron_update(X,y,T)


Caso else
[[1. 0.]]
Caso if
[[1. 0.]]
Caso else
[[ 1. -2.]]
Caso if
[[ 1. -2.]]
Caso if
[[ 1. -2.]]
Caso else
[[ 2. -1.]]
Caso if
[[ 2. -1.]]
Caso if
[[ 2. -1.]]
