In [2]:
import numpy as np
import matplotlib.pyplot as plt
# from scipy.sparse import csr_matrix
import time
import sys

# im2col

In [3]:
# Dense Method
def im2col_matrix_dense(X, K):
    N, C, H, W = X.shape
    CHW = C * H * W
    out_H = H - K + 1
    out_W = W - K + 1
    P = out_H * out_W
    patch_size = C * K * K

    # Initialize the im2col matrix with zeros
    im2col_mat = np.zeros((CHW, P * patch_size))

    patch_idx = 0
    for h in range(out_H):
        for w in range(out_W):
            for c in range(C):
                for kh in range(K):
                    for kw in range(K):
                        input_index = c * H * W + (h + kh) * W + (w + kw)
                        patch_position = c * K * K + kh * K + kw
                        output_index = patch_idx * patch_size + patch_position

                        im2col_mat[input_index, output_index] = 1
            patch_idx += 1

    return im2col_mat

# # Sparse Method
# def im2col_matrix_sparse(X, K):
#     N, C, H, W = X.shape
#     CHW = C * H * W
#     out_H = H - K + 1
#     out_W = W - K + 1
#     P = out_H * out_W
#     patch_size = C * K * K

#     data = []
#     row_indices = []
#     col_indices = []

#     patch_idx = 0
#     for h in range(out_H):
#         for w in range(out_W):
#             for c in range(C):
#                 for kh in range(K):
#                     for kw in range(K):
#                         input_index = c * H * W + (h + kh) * W + (w + kw)
#                         patch_position = c * K * K + kh * K + kw
#                         output_index = patch_idx * patch_size + patch_position

#                         data.append(1)
#                         row_indices.append(input_index)
#                         col_indices.append(output_index)
#             patch_idx += 1

#     im2col_mat_sparse = csr_matrix((data, (row_indices, col_indices)), shape=(CHW, P * patch_size))
#     return im2col_mat_sparse


# A numerical example

In [4]:
C, H, W = 2, 4, 5
K = 2  # Kernel size
N = 2  # Batch size
X = np.arange(N * C * H * W).reshape(N, C, H, W)
X[0]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [5]:
X_flat = X.reshape(N, -1)  # Shape (N, C*H*W)
X_flat[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [6]:

CHW = C * H * W
out_H = H - K + 1 # Output height
out_W = W - K + 1 # Output width
P = out_H * out_W  # Total number of patches per image
patch_size = C * K * K  # Size of each flattened patch

im2col_mat_dense = im2col_matrix_dense(X, K)
X_out_dense = np.matmul(X_flat, im2col_mat_dense)
X_patches_flat = X_out_dense.reshape(-1, P, patch_size)
X_patches = X_patches_flat.reshape(N,P,C,K,K)
X_patches.shape

(2, 12, 2, 2, 2)

In [7]:
X_patches[0,0]

array([[[ 0.,  1.],
        [ 5.,  6.]],

       [[20., 21.],
        [25., 26.]]])

In [8]:
X_out_dense

array([[ 0.,  1.,  5.,  6., 20., 21., 25., 26.,  1.,  2.,  6.,  7., 21.,
        22., 26., 27.,  2.,  3.,  7.,  8., 22., 23., 27., 28.,  3.,  4.,
         8.,  9., 23., 24., 28., 29.,  5.,  6., 10., 11., 25., 26., 30.,
        31.,  6.,  7., 11., 12., 26., 27., 31., 32.,  7.,  8., 12., 13.,
        27., 28., 32., 33.,  8.,  9., 13., 14., 28., 29., 33., 34., 10.,
        11., 15., 16., 30., 31., 35., 36., 11., 12., 16., 17., 31., 32.,
        36., 37., 12., 13., 17., 18., 32., 33., 37., 38., 13., 14., 18.,
        19., 33., 34., 38., 39.],
       [40., 41., 45., 46., 60., 61., 65., 66., 41., 42., 46., 47., 61.,
        62., 66., 67., 42., 43., 47., 48., 62., 63., 67., 68., 43., 44.,
        48., 49., 63., 64., 68., 69., 45., 46., 50., 51., 65., 66., 70.,
        71., 46., 47., 51., 52., 66., 67., 71., 72., 47., 48., 52., 53.,
        67., 68., 72., 73., 48., 49., 53., 54., 68., 69., 73., 74., 50.,
        51., 55., 56., 70., 71., 75., 76., 51., 52., 56., 57., 71., 72.,
        76., 77.,

# Exercise 3: compute X_convolved using matmul or "@"

In [9]:
# YOUR CODE HERE
# replace this dummy code
# hint: consider defining a tensor Conv_kernel of shape (2,2,2) then flattening it
X_convolved = np.zeros((2,3,4))


In [10]:
X_convolved.shape

(2, 3, 4)

In [11]:
X_convolved[0]
# expected output

# array([[ 9., 10., 11., 12.],
#        [14., 15., 16., 17.],
#        [19., 20., 21., 22.]])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])